export * from "./admin"
export * from "./user"
export * from "./enquiry"
export * from "./standard"
export * from "./attendance"
export * from "./grouphead"
export * from "./canteen"
export * from "./transportation"